AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB REST frontend

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Branch:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
  EntityRegistry:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handlers.SimpleHandler::handleRequest
      Runtime: java8
      CodeUri: api/build/libs/api-fat.jar
      MemorySize: 1512
      Role:
        Fn::ImportValue:
          !Join ['-',[!Ref ProjectId, !Ref Branch, 'LambdaTrustRole' ]]
      Timeout: 60
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref RestApi
Outputs:
  ServerlessApiValue:
    Description: URL for application
    Value: !Sub
              - 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${BranchValue}'
              - { BranchValue: !Ref Branch }
    Export:
  Name: AppRestApi


#
#  RestApiUrlParameter:
#    Type: "AWS::SSM::Parameter"
#    Properties:
#      Name: "restApiUrlParameter"
#      Type: "String"
#      Value: !Join ['', ['https://', !Ref 'RestApi', '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/',!Ref Branch]]
#      Description: "SSM Parameter for storing RestApi URL"