AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB REST frontend

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  LambdaTrustRoleArn:
    Type: String
  CodeBucket:
    Type: String
    Description: S3 Bucket containing artifacts and source code.
  Branch:
    Type: String

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
#      Cors:
#        AllowOrigin: "'*'"
      DefinitionBody:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Join ['', ['s3://', !Ref 'CodeBucket', '/openapi.yaml']]
  LambdaFunction:
    DependsOn:

    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handlers.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: api/build/libs/api-fat.jar
      MemorySize: 1512
      Role: !Ref LambdaTrustRoleArn
      Timeout: 600
      Events:
        ApiResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref RestApi

  RestApiUrlParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Join ['-', [!Ref 'ProjectId', !Ref Branch, !Ref Stage, "apiUrl"]]
      Type: "String"
      Value: !Join ['', ['https://', !Ref 'RestApi', '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref 'Stage']]
      Description: "SSM Parameter for storing RestApi URL"