AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB REST frontend


Parameters:
  ProjectId:
    Type: String
  Stage:
    Type: String
    Description: Deployment stage. E.g. test, prod, etc.
  Branch:
    Type: String
  CodeBucket:
    Type: String
  InitFunctionName:
    Type: String
  DestroyFunctionName:
    Type:  String


Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: !Join ['-',[!Ref ProjectId, !Ref Branch, !Ref Stage]]
      # Waiting for open issue to be resolved: https://github.com/awslabs/serverless-application-model/issues/627
      #      Cors: "'amazonaws.com'"
#      DefinitionBody:
#        Fn::Transform:
#          Name: 'AWS::Include'
#          Parameters:
#            Location: !Join ['', ['s3://', !Ref 'CodeBucket', '/openapi.yaml']]
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handlers.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: api/build/libs/api-fat.jar
      MemorySize: 1512
      Policies:
        Version: '2012-10-17'
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:PutLogEvents
          - dynamodb:CreateTable
          - dynamodb:DeleteTable
          - dynamodb:DescribeTable
          - dynamodb:ListTables
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:Scan
          - s3:*
          - apigateway:GET

          Resource: "*"
          Effect: Allow
        - Action:
          - secretsmanager:GetSecretValue
          - ssm:GetParameter
          Resource: "*"
          #     //The rest of the policies are for all lambda functions
          Effect: Allow
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: "*"

        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: arn:aws:s3:::*/AWSLogs/*/Config/*
        - Effect: Allow
          Action:
          - config:Put*
          - config:Get*
          - config:List*
          - config:Describe*
          Resource: "*"
      Timeout: 600
      Environment:
        Variables:
          STAGE_NAME: !Ref Stage
          API_KEY_TABLE_NAME: !Join ['-', [!Ref 'ProjectId', !Ref Branch, !Ref Stage, "apiKeys"]]
          VALIDATION_SCHEMA_TABLE_NAME: !Join ['-', [!Ref 'ProjectId', !Ref Branch, !Ref Stage, "validationSchemas"]]
      Events:
        ApiResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref RestApi
            
  SNSDynamoDBChangeTopic:          
    Description: "Common topic for signaling changes in DynamoDB"
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: String
      TopicName: !Join ['-', [!Ref 'ProjectId', !Ref Branch, "DDBChangeTopic"]]
      
  SNSDynamoDBChangeTopicPolicy:      
    Description: "Access to common topic for signaling changes in DynamoDB"
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Id: SNSDynamoDBChangeTopicPolicy
        Statement:
        - Action: 
          - sns:Publish
          - sns:ListTopics
          Effect: Allow
          Principal:
            AWS: "*"
          Resource: "*"
        Topics: 
        - !Ref SNSDynamoDBChangeTopic      
      
                  
  SNSDynamoDBChangeSubscription:          
    Description: "Subscription to common topic for signaling changes in DynamoDB"
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !Ref DynamoDBEventProcessorLambda
      Protocol: lambda
      TopicArn: !Ref SNSDynamoDBChangeTopic             
            
  DynamoDBEventProcessorLambda:
    Description: "Subscribes to common topic for signaling changes in DynamoDB"
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.db.DynamoDBEventProcessor::handleRequest
      Runtime: java8
      CodeUri: api/build/libs/api-fat.jar
      MemorySize: 1512
      Policies:
        Version: '2012-10-17'
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:PutLogEvents
          - dynamodb:CreateTable
          - dynamodb:DeleteTable
          - dynamodb:DescribeTable
          - dynamodb:ListTables
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:Scan
          - s3:*
          - apigateway:GET

          Resource: "*"
          Effect: Allow
        - Action:
          - secretsmanager:GetSecretValue
          - ssm:GetParameter
          Resource: "*"
          #     //The rest of the policies are for all lambda functions
          Effect: Allow
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: "*"

        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: arn:aws:s3:::*/AWSLogs/*/Config/*
        - Effect: Allow
          Action:
          - config:Put*
          - config:Get*
          - config:List*
          - config:Describe*
          Resource: "*"
#      Timeout: 600
#      Events:
#        DynamoDBChange:
#          Type: DynamoDB
#          Properties:
#            Enabled: true

  RestApiUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['-', [!Ref 'ProjectId', !Ref Branch, !Ref Stage, "apiUrl"]]
      Type: "String"
      Value: !Join ['', ['https://', !Ref 'RestApi', '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref 'Stage']]
      Description: "SSM Parameter for storing RestApi URL"

  Init:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handlers.InitHandler::handleRequest
      FunctionName: !Ref InitFunctionName
      Runtime: java8
      CodeUri: api/build/libs/api-fat.jar
      Policies:
        Version: '2012-10-17'
        Statement:
        - Action:
          - lambda:InvokeFunction
          - codepipeline:PutJobFailureResult
          - codepipeline:PutJobSuccessResult
          - logs:DeleteLogGroup
          - logs:DescribeLogGroups
          - apigateway:*
          - dynamodb:DescribeTable
          - dynamodb:CreateTable
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - cloudformation:DescribeStackResources
          - route53:ListHostedZones
          - route53:ChangeResourceRecordSets
          - secretsmanager:GetSecretValue
          - iam:CreateServiceLinkedRole
          Effect: Allow
          Resource: "*"
      MemorySize: 1500
      Timeout: 900
      Environment:
        Variables:
          SWAGGER_API_ID: '{{resolve:ssm:SWAGGER_API_ID:1}}'
          SWAGGER_API_VERSION: "1.0"
          SWAGGER_API_OWNER: '{{resolve:ssm:SWAGGER_API_OWNER:1}}'
          SWAGGERHUB_API_KEY_SECRET_NAME: 'swaggerapikey'
          SWAGGERHUB_API_KEY_SECRET_KEY: 'swaggerapikey'
          STAGE_NAME: !Ref Stage
          API_KEY_TABLE_NAME: !Join ['-', [!Ref 'ProjectId', !Ref Branch, !Ref Stage, "apiKeys"]]
          REGIONAL_CERTIFICATE_ARN: '{{resolve:ssm:API_ENTITYDATA_CERTIFICATE_ARN:1}}'
          HOSTED_ZONE_NAME: '{{resolve:ssm:HOSTED_ZONE_NAME:1}}'
          APPLICATION_URL: '{{resolve:ssm:APPLICATION_URL:1}}'
          STACK_NAME: !Ref AWS::StackName
          BRANCH: !Ref Branch
  Destroy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: no.bibsys.handlers.DestroyHandler::handleRequest
      FunctionName: !Ref DestroyFunctionName
      Runtime: java8
      CodeUri: api/build/libs/api-fat.jar
      Policies:
        Version: '2012-10-17'
        Statement:
        - Action:
          - lambda:InvokeFunction
          - codepipeline:PutJobFailureResult
          - codepipeline:PutJobSuccessResult
          - logs:DeleteLogGroup
          - logs:DescribeLogGroups
          - apigateway:*
          - dynamodb:DescribeTable
          - dynamodb:DeleteTable
          - cloudformation:DescribeStackResources
          - route53:ListHostedZones
          - route53:ChangeResourceRecordSets
          - secretsmanager:GetSecretValue
          Effect: Allow
          Resource: "*"
      MemorySize: 1500
      Timeout: 900
      Environment:
        Variables:
          STAGE_NAME: !Ref Stage
          API_KEY_TABLE_NAME: !Join ['-', [!Ref 'ProjectId', !Ref Branch, !Ref Stage, "apiKeys"]]
          STACK_NAME: !Ref AWS::StackName
          HOSTED_ZONE_NAME: '{{resolve:ssm:HOSTED_ZONE_NAME:1}}'
          APPLICATION_URL: '{{resolve:ssm:APPLICATION_URL:1}}'
          BRANCH: !Ref Branch
          SWAGGER_API_ID: '{{resolve:ssm:SWAGGER_API_ID:1}}'
          SWAGGER_API_VERSION: "1.0"
          SWAGGER_API_OWNER: '{{resolve:ssm:SWAGGER_API_OWNER:1}}'
          SWAGGERHUB_API_KEY_SECRET_NAME: 'swaggerapikey'
          SWAGGERHUB_API_KEY_SECRET_KEY: 'swaggerapikey'
