package no.bibsys.service;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

import no.bibsys.web.security.Roles;

public class ApiKey {

    private String key;
    private String role;
    private String registry;
    private boolean active;
    private Date modified;
    
    public ApiKey() {}
    
    public ApiKey(String role) {
        this.role = role;
        this.active = true;
    }
    
    @DynamoDBHashKey(attributeName = "Key")
    @DynamoDBAutoGeneratedKey
    public String getKey() {
        return key;
    }
    public void setKey(String key) {
        this.key = key;
    }
    @DynamoDBAttribute(attributeName = "Role")
    public String getRole() {
        return role;
    }
    public void setRole(String role) {
        this.role = role;
    }
    @DynamoDBAttribute(attributeName = "Registry")
    public String getRegistry() {
        return registry;
    }

    public void setRegistry(String registry) {
        this.registry = registry;
    }

    @DynamoDBAttribute(attributeName = "Active")
    @DynamoDBTyped(DynamoDBAttributeType.BOOL)
    public boolean isActive() {
        return active;
    }
    public void setActive(boolean active) {
        this.active = active;
    }
    @DynamoDBAttribute(attributeName = "Modified")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getModified() {
        return modified;
    }
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @DynamoDBIgnore
    public static ApiKey createApiAdminApiKey() {
        return new ApiKey(Roles.API_ADMIN);
    }
    
    @DynamoDBIgnore
    public static ApiKey createRegistryAdminApiKey(String registry) {
        ApiKey apiKey = new ApiKey(Roles.REGISTRY_ADMIN);
        apiKey.setRegistry(registry);
        return apiKey;
    }
    
}
