AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Pet Store API written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler:  no.bibsys.handlers.SampleHandler::handleRequest
      Runtime: java8
      CodeUri: target/hello-1.0-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: any
